# Generated by Django 4.2.19 on 2025-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('published_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
