# Generated by Django 4.2.19 on 2025-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
